# Generated by Django 3.1.5 on 2021-02-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
